# Generated by Django 2.0 on 2017-12-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20171220_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='finish by date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(blank=True),
        ),
    ]
