# Generated by Django 2.0 on 2017-12-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20171220_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.AddField(
            model_name='task',
            name='task_topic',
            field=models.CharField(default='No Topic', max_length=100, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Finish by date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
