# Generated by Django 2.0 on 2017-12-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20171224_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_topic',
            field=models.CharField(max_length=100, verbose_name='Topic'),
        ),
    ]
