# Generated by Django 2.0 on 2017-12-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20171224_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
    ]
